DROP DATABASE IF EXISTS game_log;

CREATE DATABASE IF NOT EXISTS game_log;

CREATE TABLE IF NOT EXISTS game_log.games (
	game_id INT PRIMARY KEY AUTO_INCREMENT,
    play_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    winner VARCHAR(100)
) ENGINE=InnoDB AUTO_INCREMENT=1001;

CREATE TABLE IF NOT EXISTS game_log.logs (
	log_id INT PRIMARY KEY AUTO_INCREMENT,
    game_id INT,
    player VARCHAR(100) NOT NULL,
    cards CHAR(8) NOT NULL,
    point TINYINT NOT NULL,
    biggest_card CHAR(2) NOT NULL,
    FOREIGN KEY (game_id) REFERENCES game_log.games(game_id)
) ENGINE=InnoDB AUTO_INCREMENT=10001;